#!/bin/sh
# /etc/init.d/aesdsocket-start-stop

DAEMON=/usr/bin/aesdsocket
DAEMON_OPTS="-d"
PIDFILE=/var/run/aesdsocket.pid

case "$1" in
  start)
    echo "Starting aesdsocket..."
    start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
    ;;
  stop)
    echo "Stopping aesdsocket..."
    start-stop-daemon --stop --quiet --pidfile $PIDFILE --signal TERM
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
